#!/usr/bin/env bash
# installing and setting up haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# listening to web01 and web02 servers
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 516618-web-01 34.207.221.247 check
    server 516618-web-02 100.26.152.41 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
