#!/usr/bin/env bash
# this script prints Best school 10 times using while and if statement

counter=0
while [ $counter -lt 10 ]; do
  if [ $counter -eq 8 ]; then
    echo "Hi"
  else
    echo "Best School"
  fi
  counter=$((counter + 1 ))
done