#!/usr/bin/env bash
# a Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for file in *; do
    # Check if the file is a regular file (not a directory) and not hidden
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        # Extract and display the part of the filename after the first dash
        echo "$file" | cut -d '-' -f 2-
    fi
done